author: Adibob
description: Changes is good.
keyword: 
favicon: /images/favicon.png

excerpt_link: Read more

menu:
 Home: /
 Categories: /categories
 Archives: /archives
 About: /about

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment, uyan or disqus

comment: false

# gitment config
gitment_owner: yanm1ng
gitment_repo: yanm1ng.github.io
gitment_oauth_id: 0f87e490e00ee3fd87ef
gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 

# disqus config
disqus_shortname: 

about: 
  banner: /images/banner.jpg
  avatar: /images/logo.jpg
  description: "Adibob have been founded since 2014. Our team's vision is to bring changes to the world. Our mission is to keep you updated with the changes that happen around you. We are focusing on the Network Environment where society have been using it everywhere. Do follow us and we feed you with these fresh news coming up."
  weibo_username: 
  twitter_username: 
  github_username: 
  zhihu_username: 
  douban_username: 
  linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
